"""
feature_engineering.py

This module contains functions to perform feature engineering on the ship delay dataset.
It creates domain-specific features like complexity-to-maturity ratio, burn rate intensity,
and cumulative delay metrics.
"""

import pandas as pd
import numpy as np
from logger import logger

def engineer_features(df: pd.DataFrame) -> pd.DataFrame:
    """
    Applies feature engineering to the dataset.
    Adds interaction, ratio, and cumulative risk indexes to help models learn.
    """
    logger.info("Engineering domain-specific features...")
    df = df.copy()
    
    # 1. Complexity to Maturity Ratio
    # High complexity combined with low technology maturity indicates high execution risk
    df["Complexity_to_Maturity"] = df["Technical_Complexity"] / (df["Technology_Maturity"] + 0.1)
    
    # 2. Cost Intensity (Crores per Month)
    # Larger financial intensity might imply stricter vendor penalties or higher administration overhead
    df["Cost_Intensity"] = df["Project_Cost"] / (df["Planned_Duration"] + 0.1)
    
    # 3. Total Administrative Delay (Days)
    # Aggregated delays before physical construction starts
    df["Total_Admin_Delay_Days"] = (
        df["Approval_Delay"] + 
        df["Tender_Delay"] + 
        df["Contract_Signing_Delay"] + 
        df["Funding_Delay"] + 
        df["Government_Clearance_Delay"]
    )
    
    # 4. Total Physical Delay (Days)
    df["Total_Execution_Delay_Days"] = df["Construction_Delay"] + df["Testing_Delay"]
    
    # 5. Quality Failure Index (QFI)
    # Weighted index where SAT failures are penalized the most, followed by FAT, inspections, and QA issues
    df["Quality_Failure_Index"] = (
        df["QA_Issues"] * 1.0 + 
        df["Inspection_Failures"] * 2.0 + 
        df["FAT_Failures"] * 4.0 + 
        df["SAT_Failures"] * 6.0
    )
    
    # 6. Vendor Risk Score
    # Combines poor vendor performance with imported equipment reliance
    df["Vendor_Risk_Score"] = (5.0 - df["Vendor_Performance"]) * (1.0 + df["Imported_Equipment"] / 100.0)
    
    # 7. Project Changes Intensity
    # Total baseline changes scaled by the planned duration (in years)
    planned_years = df["Planned_Duration"] / 12.0
    df["Changes_Intensity"] = (df["Requirement_Changes"] + df["Design_Changes"]) / (planned_years + 0.1)
    
    # 8. Risk Exposure Index
    # Product of technical complexity and open risks in the risk register
    df["Risk_Exposure"] = df["Risk_Register_Open"] * df["Technical_Complexity"]
    
    # 9. Cost-Size Ratio
    df["Cost_Per_Size_Unit"] = df["Project_Cost"] / (df["Project_Size"] + 0.01)
    
    logger.info(f"Feature engineering completed. Added 9 new features. Total columns: {len(df.columns)}")
    return df

def get_engineered_feature_names() -> list:
    """Returns the names of all features generated by engineer_features()."""
    return [
        "Complexity_to_Maturity",
        "Cost_Intensity",
        "Total_Admin_Delay_Days",
        "Total_Execution_Delay_Days",
        "Quality_Failure_Index",
        "Vendor_Risk_Score",
        "Changes_Intensity",
        "Risk_Exposure",
        "Cost_Per_Size_Unit"
    ]
